### PR TITLE
Laravel uses StyleCI

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
See the badge on the readme: https://github.com/laravel/framework. :P

**Comment by GrahamCampbell** [comment]
Why was this closed?

**Comment by ligurio** [comment]
Because I don't know what to do with this issue. There is no any problem description in it.

**Comment by GrahamCampbell** [comment]
This just makes the description clearer. More people know what Laravel is, than what Cachet is.

**Pull request closed without merging**
